### ISSUE TITLE
Socket always disconnects before final digit received

### ISSUE THREAD

**Issue by bigjosh** [Sec42/bigen#1]
Maybe a timeout someplace? 

Our application can not begin processing until all of the digits have been received, so a pretty critical issue for us.

**Comment by Sec42** [comment]
[RFC3091](https://www.ietf.org/rfc/rfc3091.txt) Section 1 states:

> One REQUIRED PIgen service is defined as a stateless TCP service.  A
> server listens on TCP port 314159.  Once a connection is established
> the server sends a stream of data, one digit of Pi at at time,
> starting with the most significant digit following the decimal point.
> Any incoming data MUST be discarded.  This continues until the client
> closes the connection.

This clearly states that the client is responsible to to close the connection, so implementing a timeout would not be conformant.

I would suggest you switch to the UDP version of this service which provides a challenge-response style protocol (defined in 2.1.1. and 2.1.2.) which may even result in bandwidth savings by being able to skip ahead to the final digit.

One downside is that you will need to implement your own timeout/retransmission logic in case a response packet gets lost.
